# Cars4You - Handout Project | Group 42
## Notebook 1 — Models Lab
**Course:** MSc in Data Science and Advanced Analytics, NOVA IMS (2025/2026)  

**Author(s):** Group 42
- `Miguel Matos - 20221925`
- `Andre Nicolau - 20221918`
- `André Ferreira - 20250398`


---

#### <font> Table of Contents </font> <a class="anchor" id='toc'></a> 
1. [Imports](#Imports)  
----

# Imports
[Back to TOC](#toc)

In [7]:
from utils.functions import *
from utils.Nuestra_Pipeline import NuestraPipeline
from Preprocessing_pipelines.Outliers_pipeline import OutliersDealer
from Preprocessing_pipelines.Missing_Values_pipeline import MissingValuesDealer
from Preprocessing_pipelines.Encoding_pipeline import EncodingDealer
from Preprocessing_pipelines.Scaling_pipeline import ScalingDealer
from Preprocessing_pipelines.Feature_Selection_pipeline import FeatureSelectionDealer

data = pd.read_csv("../data/data_cleaned.csv", index_col= "carID")
pd.set_option("display.max_columns", None)

In [8]:
data.head()

,Brand,model,car_age,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners
carID,,,,,,,,,,,,
0,Audi,A3,8.0,10990,Manual,57097.0,Diesel,0.0,83.1,1.6,75.0,4.0
1,Audi,A7,7.0,22999,Semi-Auto,24337.0,Diesel,150.0,55.4,3.0,31.0,0.0
2,Audi,A4,8.0,14242,Manual,14900.0,Petrol,125.0,53.3,1.4,65.0,4.0
3,Audi,Q3,7.0,15998,Manual,37151.0,Petrol,145.0,51.4,1.4,55.0,1.0
4,Audi,A6,5.0,30850,Automatic,4553.0,Diesel,145.0,47.9,2.0,62.0,0.0

Let's drop "model" column as we don't intend to use it and to ease inital tests.

In [9]:
data.drop("model", axis = 1, inplace= True)

In [10]:
X = data.drop("price", axis= 1)
y = data["price"]

In [11]:
#pipeline = Pipeline([ 
#           ("imputer", MissingValuesDealer()),
#           ("outliers", OutliersDealer()),
#           ("encoder", EncodingDealer()),
#           ("scaler", ScalingDealer()),
#           ("selector", FeatureSelectionDealer()),
#           ("model", RandomForestRegressor())      
#])

model_rf = RandomForestRegressor()

pipeline = NuestraPipeline(OutliersDealer(), 
                           MissingValuesDealer(),
                           EncodingDealer(), 
                           ScalingDealer(),
                           FeatureSelectionDealer(),
                           model_rf)

parameters = {
              "imputer__imputation_method": ["knn_brandwise"]
}

mae_scorer = make_scorer(mean_absolute_error, greater_is_better=False)

random_search = RandomizedSearchCV(pipeline, parameters, scoring=mae_scorer, n_iter= 2, verbose=3, refit= "mae_scorer")

In [12]:
random_search.fit(X, y)

C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 1 is smaller than n_iter=2. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 1/5] END imputer__imputation_method=knn_brandwise;, score=nan total time=   0.0s
[CV 2/5] END imputer__imputation_method=knn_brandwise;, score=nan total time=   0.0s
[CV 3/5] END imputer__imputation_method=knn_brandwise;, score=nan total time=   0.0s
[CV 4/5] END imputer__imputation_method=knn_brandwise;, score=nan total time=   0.0s
[CV 5/5] END imputer__imputation_method=knn_brandwise;, score=nan total time=   0.0s

ValueError:
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\Faculdade\Mestrado\Data Mining\Data Mining_ Materials\ML_Project_Group42\notebooks_2nd_delivery\utils\Nuestra_Pipeline.py", line 54, in fit
    X = self.imputer.fit_transform(X, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\base.py", line 894, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Faculdade\Mestrado\Data Mining\Data Mining_ Materials\ML_Project_Group42\notebooks_2nd_delivery\Preprocessing_pipelines\Missing_Values_pipeline.py", line 105, in fit
    brand_imputed = self.imputer_brand.transform(X_train_[["Brand"]])      #(TRYING THINGS TO SOLVE THE ERROR)
                                                 ^
NameError: name 'X' is not defined

It took 52 seconds to run.

Yayyyyyyy, já dá para correr istooooo.

In [ ]:
pd.DataFrame(random_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_imputer__imputation_method,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,86.125614,6.913231,13.544331,6.672484,knn,{'imputer__imputation_method': 'knn'},-4286.431664,-1500.130088,-2903.992902,-2348.874961,-2272.536907,-2662.393304,927.039212,1

In [ ]:
print("Best params:", random_search.best_params_)
print("Best score:", -random_search.best_score_)

Best params: {'imputer__imputation_method': 'knn'}
Best score: 2662.393304422333

In [ ]:
best_model = random_search.best_estimator_

In [ ]:
best_model.predict(X)

array([10529.14, 24019.41, 13913.62, ..., 20263.86, 15447.03, 17013.98],
      shape=(75973,))