# Cars4You - Handout Project | Group 42
## Notebook 1 — Models Lab
**Course:** MSc in Data Science and Advanced Analytics, NOVA IMS (2025/2026)  

**Author(s):** Group 42
- `Miguel Matos - 20221925`
- `Andre Nicolau - 20221918`
- `André Ferreira - 20250398`


---

#### <font> Table of Contents </font> <a class="anchor" id='toc'></a> 
1. [Imports](#Imports)  
----

# Imports
[Back to TOC](#toc)

In [ ]:
from utils.functions import *
from utils.Nuestra_Pipeline import NuestraPipeline
from Preprocessing_pipelines.Outliers_pipeline import OutliersDealer
from Preprocessing_pipelines.Missing_Values_pipeline import MissingValuesDealer
from Preprocessing_pipelines.Encoding_pipeline import EncodingDealer
from Preprocessing_pipelines.Scaling_pipeline import ScalingDealer
from Preprocessing_pipelines.Feature_Selection_pipeline import FeatureSelectionDealer

data = pd.read_csv("../data/data_cleaned.csv", index_col= "carID")
pd.set_option("display.max_columns", None)

In [2]:
data.head()

,Brand,model,car_age,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners
carID,,,,,,,,,,,,
0,Audi,A3,8.0,10990,Manual,57097.0,Diesel,0.0,83.1,1.6,75.0,4.0
1,Audi,A7,7.0,22999,Semi-Auto,24337.0,Diesel,150.0,55.4,3.0,31.0,0.0
2,Audi,A4,8.0,14242,Manual,14900.0,Petrol,125.0,53.3,1.4,65.0,4.0
3,Audi,Q3,7.0,15998,Manual,37151.0,Petrol,145.0,51.4,1.4,55.0,1.0
4,Audi,A6,5.0,30850,Automatic,4553.0,Diesel,145.0,47.9,2.0,62.0,0.0

Let's drop "model" column as we don't intend to use it and to ease inital tests.

In [3]:
data.drop("model", axis = 1, inplace= True)

In [4]:
X = data.drop("price", axis= 1)
y = data["price"]

In [11]:
#pipeline = Pipeline([ 
#           ("imputer", MissingValuesDealer()),
#           ("outliers", OutliersDealer()),
#           ("encoder", EncodingDealer()),
#           ("scaler", ScalingDealer()),
#           ("selector", FeatureSelectionDealer()),
#           ("model", RandomForestRegressor())      
#])

model_rf = RandomForestRegressor()

pipeline = NuestraPipeline(OutliersDealer(), 
                           MissingValuesDealer(),
                           EncodingDealer(), 
                           ScalingDealer(),
                           FeatureSelectionDealer(),
                           model_rf)

parameters = {
              "outlier_remover__threshold": [2,3]
}

mae_scorer = make_scorer(mean_absolute_error, greater_is_better=False)

random_search = RandomizedSearchCV(pipeline, parameters, scoring=mae_scorer, n_iter= 2, verbose=3, refit= "mae_scorer", n_jobs=-1)

In [12]:
random_search.fit(X, y)

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV 1/5] END ..outlier_remover__threshold=2;, score=-4327.080 total time=  24.9s
[CV 1/5] END ..outlier_remover__threshold=3;, score=-4277.921 total time=  25.4s
[CV 3/5] END ..outlier_remover__threshold=2;, score=-2833.461 total time=  25.8s
[CV 3/5] END ..outlier_remover__threshold=3;, score=-2857.644 total time=  25.8s
[CV 4/5] END ..outlier_remover__threshold=2;, score=-2280.862 total time=  26.2s
[CV 2/5] END ..outlier_remover__threshold=2;, score=-1442.098 total time=  26.4s
[CV 5/5] END ..outlier_remover__threshold=2;, score=-2303.216 total time=  26.4s
[CV 2/5] END ..outlier_remover__threshold=3;, score=-1431.799 total time=  26.7s
[CV 4/5] END ..outlier_remover__threshold=3;, score=-2277.111 total time=  18.3s
[CV 5/5] END ..outlier_remover__threshold=3;, score=-2326.996 total time=  18.6s

RandomizedSearchCV(estimator=NuestraPipeline(encoder=EncodingDealer(),
                                             imputer=MissingValuesDealer(),
                                             model=RandomForestRegressor(),
                                             outlier_remover=OutliersDealer(),
                                             scaler=ScalingDealer(),
                                             selector=FeatureSelectionDealer()),
                   n_iter=2, n_jobs=-1,
                   param_distributions={'outlier_remover__threshold': [2, 3]},
                   refit='mae_scorer',
                   scoring=make_scorer(mean_absolute_error, greater_is_better=False, response_method='predict'),
                   verbose=3)

It took 52 seconds to run.

Yayyyyyyy, já dá para correr istooooo.

In [13]:
pd.DataFrame(random_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_outlier_remover__threshold,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,25.523964,0.544852,0.430686,0.061988,2,{'outlier_remover__threshold': 2},-4327.079662,-1442.097715,-2833.461182,-2280.861644,-2303.215877,-2637.343216,955.091986,2
1,22.610969,3.662805,0.348482,0.076858,3,{'outlier_remover__threshold': 3},-4277.920594,-1431.798693,-2857.643819,-2277.111315,-2326.996062,-2634.294097,940.148922,1

In [14]:
print("Best params:", random_search.best_params_)
print("Best score:", -random_search.best_score_)

Best params: {'outlier_remover__threshold': 3}
Best score: 2634.294096743867

In [15]:
best_model = random_search.best_estimator_

In [16]:
best_model.predict(X)

array([10648.65, 23165.87, 14044.65, ..., 20324.12, 15532.23, 17020.06])