# Cars4You - Handout Project | Group 42
## Notebook 1 — Models Lab
**Course:** MSc in Data Science and Advanced Analytics, NOVA IMS (2025/2026)  

**Author(s):** Group 42
- `Miguel Matos - 20221925`
- `Andre Nicolau - 20221918`
- `André Ferreira - 20250398`


---

#### <font> Table of Contents </font> <a class="anchor" id='toc'></a> 
1. [Imports](#Imports)  
----

# Imports
[Back to TOC](#toc)

In [12]:
from utils.functions import *
from utils.Nuestra_Pipeline import NuestraPipeline
from Preprocessing_pipelines.Outliers_pipeline import OutliersDealer
from Preprocessing_pipelines.Missing_Values_pipeline import MissingValuesDealer
from Preprocessing_pipelines.Encoding_pipeline import EncodingDealer
from Preprocessing_pipelines.Scaling_pipeline import ScalingDealer
from Preprocessing_pipelines.Feature_Selection_pipeline import FeatureSelectionDealer


data = pd.read_csv("../data/data_cleaned.csv", index_col= "carID")
pd.set_option("display.max_columns", None)

In [13]:
data = data.sample(frac=1).reset_index(drop=True)

In [14]:
data.head()

,Brand,model,car_age,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners
0,Audi,A4,7.0,13990,Manual,60000.0,Diesel,145.0,68.9,2.0,43.0,4.0
1,BMW,2 serie,15.0,6950,Manual,78000.0,Diesel,125.0,58.9,2.0,64.0,4.0
2,Audi,Q5,5.0,38691,Automatic,10.0,Diesel,145.0,38.2,2.0,54.0,2.0
3,Opel,Insignia,6.0,14640,Manual,27089.0,Petrol,145.0,50.4,1.5,75.0,1.0
4,Toyota,Yaris,10.0,6775,Unknown,29000.0,Petrol,30.0,58.0,1.3,NaN,3.0

Let's drop "model" column as we don't intend to use it and to ease inital tests.

In [15]:
data.drop("model", axis = 1, inplace= True)

In [16]:
X = data.drop("price", axis= 1)
y = data["price"]

In [17]:
#pipeline = Pipeline([ 
#           ("imputer", MissingValuesDealer()),
#           ("outliers", OutliersDealer()),
#           ("encoder", EncodingDealer()),
#           ("scaler", ScalingDealer()),
#           ("selector", FeatureSelectionDealer()),
#           ("model", RandomForestRegressor())      
#])

model_rf = RandomForestRegressor()

pipeline = NuestraPipeline(OutliersDealer(), 
                           MissingValuesDealer(),
                           EncodingDealer(), 
                           ScalingDealer(),
                           FeatureSelectionDealer(),
                           model_rf)

parameters = [{
              "imputer__imputation_method": ["knn_brandwise", "knn", "simple", "iterative"],
              "imputer__knn_neighbors": np.arange(10,21),
              "imputer__knn_scaling_method" : ["standard", "minmax", "robust"],
              "outlier_remover__outlier_method" : ["z_score", "IQR", "Isolation_Forest", "LOF"],
              "outlier_remover__mod_outliers_cols" : [["car_age", "mileage", "tax", "mpg"], ["tax", "mpg"]],
              "outlier_remover__sev_outliers_cols" : [["car_age", "mileage", "engineSize"], ["car_age", "mileage"]],
              "outlier_remover__threshold" : [2,3],
              "outlier_remover__z_columns" : ["car_age", "mileage", "tax", "mpg"],
              "outlier_remover__contamination_IF" : [0.05, 0.15, 0.3, 0.5],
              "outlier_remover__n_neighbors": [30, 50, 70, 90, 100],
              "outlier_remover__contamination_LOF" : [0.05, 0.15, 0.3, 0.5],
              "outlier_remover__model_columns" : [["car_age", "mileage", "tax", "mpg"], ["car_age", "mileage", "tax", "mpg", "engineSize"]],
              "encoder__method" : ["onehot"],
              "scaler__scaler_name" : ["robust", "minmax", "standard"]

}]

mae_scorer = make_scorer(mean_absolute_error, greater_is_better=False)

random_search = HalvingRandomSearchCV(pipeline,
                                        parameters,
                                        scoring=mae_scorer,
                                        n_candidates= 1,
                                        verbose=3,
                                        min_resources=5000,
                                        refit= "mae_scorer")

In [18]:
random_search.fit(X, y)

n_iterations: 1
n_required_iterations: 1
n_possible_iterations: 3
min_resources_: 5000
max_resources_: 75973
aggressive_elimination: False
factor: 3
----------
iter: 0
n_candidates: 1
n_resources: 5000
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 1/5] END encoder__method=onehot, imputer__imputation_method=iterative, imputer__knn_neighbors=13, imputer__knn_scaling_method=standard, outlier_remover__contamination_IF=0.05, outlier_remover__contamination_LOF=0.05, outlier_remover__mod_outliers_cols=['car_age', 'mileage', 'tax', 'mpg'], outlier_remover__model_columns=['car_age', 'mileage', 'tax', 'mpg'], outlier_remover__n_neighbors=90, outlier_remover__outlier_method=Isolation_Forest, outlier_remover__sev_outliers_cols=['car_age', 'mileage', 'engineSize'], outlier_remover__threshold=2, outlier_remover__z_columns=mileage, scaler__scaler_name=standard;, score=(train=nan, test=nan) total time=   0.4s
[CV 2/5] END encoder__method=onehot, imputer__imputation_method=iterative, imputer__knn_neighbors=13, imputer__knn_scaling_method=standard, outlier_remover__contamination_IF=0.05, outlier_remover__contamination_LOF=0.05, outlier_remover__mod_outliers_cols=['car_age', 'mileage', 'tax', 'mpg'], outlier_remover__model_columns=['car_age', 'mileage', 'tax', 'mpg'], outlier_remover__n_neighbors=90, outlier_remover__outlier_method=Isolation_Forest, outlier_remover__sev_outliers_cols=['car_age', 'mileage', 'engineSize'], outlier_remover__threshold=2, outlier_remover__z_columns=mileage, scaler__scaler_name=standard;, score=(train=nan, test=nan) total time=   0.2s
[CV 3/5] END encoder__method=onehot, imputer__imputation_method=iterative, imputer__knn_neighbors=13, imputer__knn_scaling_method=standard, outlier_remover__contamination_IF=0.05, outlier_remover__contamination_LOF=0.05, outlier_remover__mod_outliers_cols=['car_age', 'mileage', 'tax', 'mpg'], outlier_remover__model_columns=['car_age', 'mileage', 'tax', 'mpg'], outlier_remover__n_neighbors=90, outlier_remover__outlier_method=Isolation_Forest, outlier_remover__sev_outliers_cols=['car_age', 'mileage', 'engineSize'], outlier_remover__threshold=2, outlier_remover__z_columns=mileage, scaler__scaler_name=standard;, score=(train=nan, test=nan) total time=   0.3s
[CV 4/5] END encoder__method=onehot, imputer__imputation_method=iterative, imputer__knn_neighbors=13, imputer__knn_scaling_method=standard, outlier_remover__contamination_IF=0.05, outlier_remover__contamination_LOF=0.05, outlier_remover__mod_outliers_cols=['car_age', 'mileage', 'tax', 'mpg'], outlier_remover__model_columns=['car_age', 'mileage', 'tax', 'mpg'], outlier_remover__n_neighbors=90, outlier_remover__outlier_method=Isolation_Forest, outlier_remover__sev_outliers_cols=['car_age', 'mileage', 'engineSize'], outlier_remover__threshold=2, outlier_remover__z_columns=mileage, scaler__scaler_name=standard;, score=(train=nan, test=nan) total time=   0.2s
[CV 5/5] END encoder__method=onehot, imputer__imputation_method=iterative, imputer__knn_neighbors=13, imputer__knn_scaling_method=standard, outlier_remover__contamination_IF=0.05, outlier_remover__contamination_LOF=0.05, outlier_remover__mod_outliers_cols=['car_age', 'mileage', 'tax', 'mpg'], outlier_remover__model_columns=['car_age', 'mileage', 'tax', 'mpg'], outlier_remover__n_neighbors=90, outlier_remover__outlier_method=Isolation_Forest, outlier_remover__sev_outliers_cols=['car_age', 'mileage', 'engineSize'], outlier_remover__threshold=2, outlier_remover__z_columns=mileage, scaler__scaler_name=standard;, score=(train=nan, test=nan) total time=   0.2s

ValueError:
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\Faculdade\Mestrado\Data Mining\Data Mining_ Materials\ML_Project_Group42\notebooks_2nd_delivery\utils\Nuestra_Pipeline.py", line 64, in fit
    self.model_.fit(X_clean, y)
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_forest.py", line 421, in fit
    y = np.ascontiguousarray(y, dtype=DOUBLE)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'Toyota'

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\Faculdade\Mestrado\Data Mining\Data Mining_ Materials\ML_Project_Group42\notebooks_2nd_delivery\utils\Nuestra_Pipeline.py", line 64, in fit
    self.model_.fit(X_clean, y)
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_forest.py", line 421, in fit
    y = np.ascontiguousarray(y, dtype=DOUBLE)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'Ford'

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\Faculdade\Mestrado\Data Mining\Data Mining_ Materials\ML_Project_Group42\notebooks_2nd_delivery\utils\Nuestra_Pipeline.py", line 64, in fit
    self.model_.fit(X_clean, y)
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_forest.py", line 421, in fit
    y = np.ascontiguousarray(y, dtype=DOUBLE)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'Audi'

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\Faculdade\Mestrado\Data Mining\Data Mining_ Materials\ML_Project_Group42\notebooks_2nd_delivery\utils\Nuestra_Pipeline.py", line 64, in fit
    self.model_.fit(X_clean, y)
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\ensemble\_forest.py", line 421, in fit
    y = np.ascontiguousarray(y, dtype=DOUBLE)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'VW'

It took 52 seconds to run.

Yayyyyyyy, já dá para correr istooooo.

In [ ]:
pd.DataFrame(random_search.cv_results_)

,iter,n_resources,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_scaler__scaler_name,param_outlier_remover__z_columns,param_outlier_remover__threshold,param_outlier_remover__sev_outliers_cols,param_outlier_remover__outlier_method,param_outlier_remover__n_neighbors,param_outlier_remover__model_columns,param_outlier_remover__mod_outliers_cols,param_outlier_remover__contamination_LOF,param_outlier_remover__contamination_IF,param_imputer__knn_scaling_method,param_imputer__knn_neighbors,param_imputer__imputation_method,param_encoder__method,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,0,5000,1.886578,0.032768,0.032174,0.001156,minmax,car_age,3,"[car_age, mileage]",IQR,100,"[car_age, mileage, tax, mpg]","[tax, mpg]",0.5,0.5,minmax,19,simple,onehot,"{'scaler__scaler_name': 'minmax', 'outlier_rem...",-2096.9222,-2130.40253,-1960.18979,-2029.798378,-2367.350541,-2116.932688,138.167783,1,-797.221063,-777.405336,-831.71902,-782.911412,-789.744193,-795.800205,19.148616

In [ ]:
print("Best params:", random_search.best_params_)
print("Best score:", -random_search.best_score_)

Best params: {'scaler__scaler_name': 'minmax', 'outlier_remover__z_columns': 'car_age', 'outlier_remover__threshold': 3, 'outlier_remover__sev_outliers_cols': ['car_age', 'mileage'], 'outlier_remover__outlier_method': 'IQR', 'outlier_remover__n_neighbors': 100, 'outlier_remover__model_columns': ['car_age', 'mileage', 'tax', 'mpg'], 'outlier_remover__mod_outliers_cols': ['tax', 'mpg'], 'outlier_remover__contamination_LOF': 0.5, 'outlier_remover__contamination_IF': 0.5, 'imputer__knn_scaling_method': 'minmax', 'imputer__knn_neighbors': np.int64(19), 'imputer__imputation_method': 'simple', 'encoder__method': 'onehot'}
Best score: 2116.932687783784

In [ ]:
best_model = random_search.best_estimator_

In [ ]:
best_model.predict(X)

array([42724.19, 32834.51, 19896.78, ..., 10750.49, 16027.54, 14335.34],
      shape=(75973,))