# Cars4You - Handout Project | Group 42
## Notebook 1 — Models Lab
**Course:** MSc in Data Science and Advanced Analytics, NOVA IMS (2025/2026)  

**Author(s):** Group 42
- `Miguel Matos - 20221925`
- `Andre Nicolau - 20221918`
- `André Ferreira - 20250398`


---

#### <font> Table of Contents </font> <a class="anchor" id='toc'></a> 
1. [Imports](#Imports)  
2. [Modelling Testing](#modelling-testing) 
3. [Random Search](#random-search)
----

# Imports
[Back to TOC](#toc)

In [1]:
from utils.functions import *
from utils.Nuestra_Pipeline import NuestraPipeline
from Preprocessing_pipelines.Outliers_pipeline import OutliersDealer
from Preprocessing_pipelines.Missing_Values_pipeline import MissingValuesDealer
from Preprocessing_pipelines.Encoding_pipeline import EncodingDealer
from Preprocessing_pipelines.Scaling_pipeline import ScalingDealer
from Preprocessing_pipelines.Feature_Selection_pipeline import FeatureSelectionDealer

# explicitly require this experimental feature
from sklearn.experimental import enable_halving_search_cv 
# now you can import normally from model_selection
from sklearn.model_selection import HalvingRandomSearchCV

data = pd.read_csv("../data/data_cleaned.csv", index_col= "carID")
pd.set_option("display.max_columns", None)

In [2]:
data.head()

,Brand,model,car_age,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners
carID,,,,,,,,,,,,
0,Audi,A3,8.0,10990,Manual,57097.0,Diesel,0.0,83.1,1.6,75.0,4.0
1,Audi,A7,7.0,22999,Semi-Auto,24337.0,Diesel,150.0,55.4,3.0,31.0,0.0
2,Audi,A4,8.0,14242,Manual,14900.0,Petrol,125.0,53.3,1.4,65.0,4.0
3,Audi,Q3,7.0,15998,Manual,37151.0,Petrol,145.0,51.4,1.4,55.0,1.0
4,Audi,A6,5.0,30850,Automatic,4553.0,Diesel,145.0,47.9,2.0,62.0,0.0

Let's drop "model" column as we don't intend to use it and to ease inital tests.

In [3]:
data.drop("model", axis = 1, inplace= True)

Now, we'lll drop the missing values of "Brand", so that we can strtify the split on it.

In [4]:
data.dropna(subset=["Brand"], inplace=True)

In [5]:
cars_data = data.drop("price", axis= 1)
target = data["price"]

# Modelling Testing

Frist, let's do some basic cleaning for the data.

In [6]:
X_train, X_val, y_train, y_val = train_test_split(cars_data, target, 
                                                    test_size= 0.3, 
                                                    random_state= 7, # 7 because of Ronaldo :)
                                                    shuffle= True, # True, because the data is ordered by brands
                                                    stratify = cars_data["Brand"])

Data preprocessing on trainning data.

In [7]:
od = OutliersDealer()
mvd = MissingValuesDealer()
ed = EncodingDealer()
sd = ScalingDealer()
fsd = FeatureSelectionDealer(selection_method="kbest")

In [8]:
X_train = od.fit_transform(X_train)
X_train = mvd.fit_transform(X_train)
X_train = ed.fit_transform(X_train)
X_train = sd.fit_transform(X_train)
X_train = fsd.fit_transform(X_train, y_train)

Data preprocessing on validation data.

In [9]:
X_val = mvd.transform(X_val)
X_val = ed.transform(X_val)
X_val = sd.transform(X_val)
X_val = fsd.transform(X_val, y_val)

We'll start by conducting some initial tests to delete some options and making ou halving random search more effective.

In [13]:
lr = LinearRegression().fit(X_train, y_train)
lr_pred = lr.predict(X_val)
r2, mae, rmse = calculate_regression_metrics(y_val, lr_pred)
print(f"MAE: {mae}")

MAE: 3320.6072558580095

In [14]:
rf = RandomForestRegressor().fit(X_train, y_train)
rf_pred = rf.predict(X_val)
r2, mae, rmse = calculate_regression_metrics(y_val, rf_pred)
print(f"MAE: {mae}")

MAE: 1835.6372542277907

In [18]:
dt = DecisionTreeRegressor().fit(X_train, y_train)
dt_pred = dt.predict(X_val)
r2, mae, rmse = calculate_regression_metrics(y_val, dt_pred)
print(f"MAE: {mae}")

MAE: 2307.192162491222

In [19]:
dt = GradientBoostingRegressor().fit(X_train, y_train)
dt_pred = dt.predict(X_val)
r2, mae, rmse = calculate_regression_metrics(y_val, dt_pred)
print(f"MAE: {mae}")

MAE: 2443.806237065696

# Random Search

In [ ]:
#pipeline = Pipeline([ 
#           ("imputer", MissingValuesDealer()),
#           ("outliers", OutliersDealer()),
#           ("encoder", EncodingDealer()),
#           ("scaler", ScalingDealer()),
#           ("selector", FeatureSelectionDealer()),
#           ("model", RandomForestRegressor())      
#])

model_rf = RandomForestRegressor()

pipeline = NuestraPipeline(OutliersDealer(), 
                           MissingValuesDealer(),
                           EncodingDealer(), 
                           ScalingDealer(),
                           FeatureSelectionDealer(),
                           model_rf)

#parameters = {
#              "outlier_remover__threshold": [2,3]
#}

parameters = {
              "imputer__imputation_method": ["knn_brandwise", "simple"]
}

mae_scorer = make_scorer(mean_absolute_error, greater_is_better=False)

random_search = HalvingRandomSearchCV(pipeline, parameters, scoring=mae_scorer, verbose=3, min_resources= 5000, refit= "mae_scorer", n_jobs=-1)

In [43]:
random_search.fit(X, y)

n_iterations: 1
n_required_iterations: 1
n_possible_iterations: 3
min_resources_: 5000
max_resources_: 75973
aggressive_elimination: False
factor: 3
----------
iter: 0
n_candidates: 2
n_resources: 5000
Fitting 5 folds for each of 2 candidates, totalling 10 fits

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/model_selection/_search.py:320: UserWarning: The total space of parameters 2 is smaller than n_iter=15. Running 2 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

[CV 4/5] END imputer__imputation_method=knn_brandwise;, score=(train=nan, test=nan) total time=   0.0s
[CV 3/5] END imputer__imputation_method=knn_brandwise;, score=(train=nan, test=nan) total time=   0.0s
[CV 5/5] END imputer__imputation_method=knn_brandwise;, score=(train=nan, test=nan) total time=   0.0s
[CV 2/5] END imputer__imputation_method=knn_brandwise;, score=(train=nan, test=nan) total time=   0.0s
[CV 1/5] END imputer__imputation_method=knn_brandwise;, score=(train=nan, test=nan) total time=   0.0s
[CV 1/5] END imputer__imputation_method=simple;, score=(train=-712.733, test=-4387.358) total time=   1.2s
[CV 4/5] END imputer__imputation_method=simple;, score=(train=-861.885, test=-2429.647) total time=   1.1s
[CV 2/5] END imputer__imputation_method=simple;, score=(train=-838.183, test=-1944.069) total time=   1.2s
[CV 5/5] END imputer__imputation_method=simple;, score=(train=-844.133, test=-2462.545) total time=   1.2s
[CV 3/5] END imputer__imputation_method=simple;, score=(train=-723.032, test=-3473.754) total time=   1.2s

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning:
5 fits failed out of a total of 10.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/miguelmatos/Documents/GitHub/Machine_Learning_project/ML_Project_Group42/notebooks_2nd_delivery/utils/Nuestra_Pipeline.py", line 54, in fit
    X = self.imputer.fit_transform(X, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py", line 1098, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miguelmatos/Documents/GitHub/Machine_Learning_project/ML_Project_Group42/notebooks_2nd_delivery/Preprocessing_pipelines/Missing_Values_pipeline.py", line 103, in fit
    X_train_["Brand"] = self.imputer_brand.transform(X_train_[["Brand"]])
    ~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/core/frame.py", line 4311, in __setitem__
    self._set_item(key, value)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/core/frame.py", line 4524, in _set_item
    value, refs = self._sanitize_column(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/core/frame.py", line 5267, in _sanitize_column
    arr = sanitize_array(value, self.index, copy=True, allow_2d=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/core/construction.py", line 606, in sanitize_array
    subarr = maybe_infer_to_datetimelike(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/core/dtypes/cast.py", line 1181, in maybe_infer_to_datetimelike
    raise ValueError(value.ndim)  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 2

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/model_selection/_search.py:1103: UserWarning: One or more of the test scores are non-finite: [           nan -2939.47471043]
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/model_selection/_search.py:1103: UserWarning: One or more of the train scores are non-finite: [          nan -795.99336976]
  warnings.warn(

HalvingRandomSearchCV(estimator=NuestraPipeline(encoder=EncodingDealer(),
                                                imputer=MissingValuesDealer(),
                                                model=RandomForestRegressor(),
                                                outlier_remover=OutliersDealer(),
                                                scaler=ScalingDealer(),
                                                selector=FeatureSelectionDealer()),
                      min_resources=5000, n_jobs=-1,
                      param_distributions={'imputer__imputation_method': ['knn_brandwise',
                                                                          'simple']},
                      refit='mae_scorer',
                      scoring=make_scorer(mean_absolute_error, greater_is_better=False, response_method='predict'),
                      verbose=3)

In [36]:
pd.DataFrame(random_search.cv_results_)

,iter,n_resources,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_imputer__imputation_method,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,0,5000,1.539071,0.028237,0.071056,0.018537,knn,{'imputer__imputation_method': 'knn'},-4462.29935,-1960.65207,-3594.81425,-2449.113854,-2431.735796,-2979.723064,916.156262,1,-717.777992,-905.261295,-738.71895,-821.933283,-833.733817,-803.485067,68.050095

In [37]:
print("Best params:", random_search.best_params_)
print("Best score:", -random_search.best_score_)

Best params: {'imputer__imputation_method': 'knn'}
Best score: 2979.7230639299296

In [38]:
best_model = random_search.best_estimator_

In [39]:
best_model.predict(X)

array([10635.34, 23938.32, 14208.66, ..., 20479.04, 15321.92, 16701.61])